
export enum CATEGORY_PROCESS {
    DTE_FACTURA = "DTE-factura",
}


export enum TIPO_PERMISO {
    VISTA = "VIEW",
}

export enum PERMISO_RECURSO {
    FACTURA = "FACTURA",
}


export enum facturaEstado {
    PROCESANDO = "PROCESANDO",
    PENDIENTE_AUTORIZACION = "PENDIENTE_AUTORIZACION",
    PENDIENTE_VALIDACION = "PENDIENTE_VALIDACION",
    PUBLICADA = "PUBLICADA",
    OFERTADA = "OFERTADA",
    FINANCIADA = "FINANCIADA",
    PAGADA = "PAGADA",
    RECHAZADA = "RECHAZADA",
    CANCELADA = "CANCELADA",
    VENCIDA = "VENCIDA",
    DENUNCIADA = "DENUNCIADA",
}

export enum EVENT_CODES {
    FACTURA_PENDIENTE_AUTORIZACION = "PENDIENTE_AUTORIZACION",
    FACTURA_PUBLICADA = "FACTURA_PUBLICADA",
    FACTURA_PUBLICADA_PENDIENTE_VALIDACION = "FACTURA_PUBLICADA_PENDIENTE_VALIDACION",
    FACTURA_VACIA_PUBLICADA = "FACTURA_VACIA_PUBLICADA",
    FACTURA_DUPLICADA = "FACTURA_DUPLICADA",
    FACTURA_PROCESADA = "FACTURA_PROCESADA",
    FACTURA_ERROR_PROCESAMIENTO = "FACTURA_ERROR_PROCESAMIENTO",
    FACTURA_ERROR_VALIDACION = "FACTURA_ERROR_VALIDACION",
}

export enum EVENT_DESCRIPTIONS {
    FACTURA_PENDIENTE_AUTORIZACION = "Factura pendiente de autorización, debe autorizar para poder publicar la factura",
    FACTURA_PUBLICADA = "Factura publicada exitosamente",
    FACTURA_VACIA_PUBLICADA = "Factura vacía publicada exitosamente",
    FACTURA_DUPLICADA = "Factura duplicada, ya existe una factura con el mismo emisor y folio",
    FACTURA_PROCESADA = "Factura procesada exitosamente",
    FACTURA_ERROR_PROCESAMIENTO = "Error al procesar la factura",
    FACTURA_ERROR_VALIDACION = "Error de validación de la factura, Usuario u organización no válidos",
    FACTURA_PUBLICADA_PENDIENTE_VALIDACION = "Factura publicada exitosamente, pendiente de validación",
}

export enum ROLE_PERMISSION_CODES {
    SUPER_ADMIN = "SUPER_ADMIN",
    ADMIN = "ADMIN",
    SUPERVISOR = "SUPERVISOR",
    USR_STD = "USR_STD",
    READ_ONLY = "READ_ONLY",
    CLIENTE_CEDENTE = "CLIENTE_CEDENTE",
    EJECUTIVO_FINANCIADORA = "EJECUTIVO_FINANCIADORA",
    ADMIN_FINANCIADORA = "ADMIN_FINANCIADORA",
    ADMIN_CEDENTE = "ADMIN_CEDENTE",
}

export enum TIPO_PARTICIPANTE {
    CEDENTE = "CEDENTE",
    FINANCIADORA = "FINANCIADORA",
}